/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.21.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.openapitools.api

import org.openapitools.model.NotFoundError
import org.openapitools.model.Order
import org.openapitools.model.UpdateOrder422Response
import org.openapitools.model.UpdateOrderRequest
import org.openapitools.model.ValidationError
import org.openapitools.model.GetOrderResponse
import org.openapitools.model.UpdateOrderResponse
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid

import kotlin.collections.List
import kotlin.collections.Map

@RestController
@Validated
interface OrdersApi {


    @RequestMapping(
        method = [RequestMethod.GET],
        // "/orders/{orderId}"
        value = [PATH_GET_ORDER],
        produces = ["application/json"]
    )
    fun getOrder(
        @PathVariable("orderId") orderId: kotlin.String
    ): ResponseEntity<GetOrderResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }


    @RequestMapping(
        method = [RequestMethod.PATCH],
        // "/orders/{orderId}"
        value = [PATH_UPDATE_ORDER],
        produces = ["application/json"],
        consumes = ["application/json"]
    )
    fun updateOrder(
        @PathVariable("orderId") orderId: kotlin.String,
        @Valid @RequestBody updateOrderRequest: UpdateOrderRequest
    ): ResponseEntity<UpdateOrderResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    companion object {
        //for your own safety never directly reuse these path definitions in tests
        const val PATH_GET_ORDER: String = "/orders/{orderId}"
        const val PATH_UPDATE_ORDER: String = "/orders/{orderId}"
    }
}
